use_frameworks!

platform :ios, '9.0'

target 'TestingForPod_Example' do
  pod 'TestingForPod', :path => '../'

  target 'TestingForPod_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
